# Generated by Django 4.1.1 on 2022-11-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_Name', models.CharField(max_length=50)),
                ('user_DOB', models.CharField(max_length=50)),
                ('user_Gender', models.BooleanField(default=False)),
                ('user_Email', models.EmailField(max_length=254)),
                ('user_Mobile', models.CharField(max_length=10)),
                ('user_UserName', models.CharField(max_length=50)),
                ('user_PWD', models.CharField(max_length=250)),
                ('user_is_Active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_tbl',
            },
        ),
    ]
